### ISSUE TITLE
process.cwd() instead of process.cwd in path.resolve invocation

### ISSUE THREAD

**Issue by typhonrt** [istanbuljs/istanbul-lib-source-maps#1]
https://github.com/istanbuljs/istanbul-lib-source-maps/blob/master/lib/pathutils.js#L12

It seems like the above invocation of `path.resolve` should be:
`return isAbsolute(file) ? file : path.resolve(baseDir || process.cwd(), file);`

as path.resolve expects a string (`process.cwd()`) and not a function (`process.cwd`) if `baseDir` is null.

**Comment by gotwarlost** [comment]
Fixed via https://github.com/istanbuljs/istanbul-lib-source-maps/commit/d7f0dd43870e38762279e77c3146ad2247a643ee - thanks for the report!
