### ISSUE TITLE
Is it possible to suppress "nothing could be mapped" errors?

### ISSUE THREAD

**Issue by ben-eb** [istanbuljs/istanbul-lib-source-maps#9]
Due to the way that I am managing modules in a monorepo, I get a ton of these warnings which clutter up the test runner output - it'd be really good to be able to set a flag in https://github.com/istanbuljs/nyc to suppress them, or failing that, some duplicate error checking.

Right now I'm getting 260 errors that are reporting "nothing could be mapped" from 4 different files (that's the same message logged 65 times for each file), it's not a great developer experience. 😄 

The offending line is https://github.com/istanbuljs/istanbul-lib-source-maps/blob/master/lib/transformer.js#L169-L171. I am willing to submit a patch depending on what direction you guys want to go in with this.

**Comment by bcoe** [comment]
@ben-eb sorry for the slow reply; have been busily working to migrate some of the open-source projects that I contribute to to monorepos (in an attempt to reduce maintenance overhead).

Could I convince to reopen this issue on the istanbuljs monorepo? 

https://github.com/istanbuljs/istanbuljs

I'd be quite happy to accept a patch for this behavior! I wonder if, better still, we could figure out the underlying cause of all these mapping failures? what about running in a monorepo brings this warning to the forefront?

**Comment by ben-eb** [comment]
@bcoe It's probably also due to using https://github.com/tleunen/babel-plugin-module-resolver - in order to use the source files and not the transpiled `dist` folder I have to maintain a map of aliases. I guess istanbul then considers this to be a non-instrumented file and so prints the warning again?

Transpilation is hard. 😞 

Which implementation works better for you - `silent` flag or a duplicate error message checker (ala https://github.com/ben-eb/cssnano/blob/51e3e1d450e60581d687c3e23ff66d418d5d435a/src/lib/warnOnce.js)? I can surely send a PR to your monorepo instead. 👍
